name: Titan TV APK Build
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4 # v2'den v4'e güncellendi

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5 # v4'ten v5'e güncellendi
        with:
          python-version: '3.10'

      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip ant autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --upgrade pip
          pip install --user --upgrade buildozer cython==0.29.33

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Paketleme işlemi
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4 # İŞTE BURASI v4 OLARAK GÜNCELLENDİ
        with:
          name: Titan-TV-Build-${{ steps.get-date.outputs.date }}
          path: bin/*.apk
          
